name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  TEST_OUTPUT_DIR: ${{ github.workspace }}/test/reports

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1


