name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  TEST_OUTPUT_DIR: ${{ github.workspace }}/test/reports

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Run Protoc lint
        run: |
          go install github.com/ckaznocha/protoc-gen-lint@latest
          protoc --lint_out=. \
          --lint_opt=Mconfig/cache/v1alpha1/cache.proto=github.com/gingersnap-project/operator/api/v1alpha1,\
          Mconfig/cache/v1alpha1/rules.proto=github.com/gingersnap-project/operator/api/v1alpha1 \
          config/cache/v1alpha1/*.proto

